Error al reintentar autenticaciÃ³n: 'dict' object has no attribute 'headers'
