ERROR 2025-04-19 16:45:51,884 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 16:45:52,142 log Bad Request: /
ERROR 2025-04-19 16:47:04,637 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 16:47:04,638 log Bad Request: /
ERROR 2025-04-19 16:47:05,840 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 16:47:05,842 log Bad Request: /
ERROR 2025-04-19 16:47:20,152 middleware Error en /: home.html
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/api/views.py", line 13, in get
    return render(request, 'home.html')
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
ERROR 2025-04-19 16:47:20,154 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/api/views.py", line 13, in get
    return render(request, 'home.html')
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
WARNING 2025-04-19 16:48:49,972 log Not Found: /favicon.ico
WARNING 2025-04-19 16:50:49,564 log Not Found: /favicon.ico
WARNING 2025-04-19 16:50:54,150 log Not Found: /favicon.ico
ERROR 2025-04-19 18:31:47,943 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 18:31:48,492 log Bad Request: /
ERROR 2025-04-19 18:31:48,571 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 18:31:48,573 log Bad Request: /favicon.ico
ERROR 2025-04-19 18:32:39,273 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 18:32:39,519 log Bad Request: /
ERROR 2025-04-19 18:33:58,028 log Internal Server Error: /app/sct/initiate/
ERROR 2025-04-19 18:36:28,996 log Internal Server Error: /app/sct/initiate/
WARNING 2025-04-19 20:51:37,757 log Bad Request: /app/sct/initiate/
ERROR 2025-04-19 21:05:15,720 log Internal Server Error: /app/sct/initiate/
ERROR 2025-04-19 21:15:03,866 log Internal Server Error: /app/sct/initiate/
WARNING 2025-04-20 02:28:23,917 log Not Found: /favicon.ico
ERROR 2025-04-20 02:28:38,650 middleware Error en /app/gpt/transfer/initiate/: Reverse for 'create_debtorGPT' not found. 'create_debtorGPT' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 83, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_debtorGPT' not found. 'create_debtorGPT' is not a valid view function or pattern name.
ERROR 2025-04-20 02:28:38,662 log Internal Server Error: /app/gpt/transfer/initiate/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 83, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_debtorGPT' not found. 'create_debtorGPT' is not a valid view function or pattern name.
ERROR 2025-04-20 02:29:31,675 middleware Error en /app/gpt/transfer/initiate/: Reverse for 'create_debtorGPT' not found. 'create_debtorGPT' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 83, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_debtorGPT' not found. 'create_debtorGPT' is not a valid view function or pattern name.
ERROR 2025-04-20 02:29:31,683 log Internal Server Error: /app/gpt/transfer/initiate/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 83, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_debtorGPT' not found. 'create_debtorGPT' is not a valid view function or pattern name.
ERROR 2025-04-20 02:37:45,558 middleware Error en /app/gpt/transfer/initiate/: Reverse for 'create_party' not found. 'create_party' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 86, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_party' not found. 'create_party' is not a valid view function or pattern name.
ERROR 2025-04-20 02:37:45,571 log Internal Server Error: /app/gpt/transfer/initiate/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 86, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_party' not found. 'create_party' is not a valid view function or pattern name.
ERROR 2025-04-20 02:39:21,486 middleware Error en /app/gpt/transfer/initiate/: Reverse for 'transfer_list_view' not found. 'transfer_list_view' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 86, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'transfer_list_view' not found. 'transfer_list_view' is not a valid view function or pattern name.
ERROR 2025-04-20 02:39:21,489 log Internal Server Error: /app/gpt/transfer/initiate/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 86, in initiate_sepa_transfer
    return render(request, 'api/GPT/initiate_transfer.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'transfer_list_view' not found. 'transfer_list_view' is not a valid view function or pattern name.
ERROR 2025-04-20 04:09:50,254 middleware Error en /app/dashboard/: Reverse for 'create_partyGPT' not found. 'create_partyGPT' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/views.py", line 39, in get
    return render(request, 'dashboard.html')
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_partyGPT' not found. 'create_partyGPT' is not a valid view function or pattern name.
ERROR 2025-04-20 04:09:50,265 log Internal Server Error: /app/dashboard/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/views.py", line 39, in get
    return render(request, 'dashboard.html')
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_partyGPT' not found. 'create_partyGPT' is not a valid view function or pattern name.
ERROR 2025-04-20 04:11:58,175 middleware Error en /app/gpt/create/debtor/: Reverse for 'create_addressGPT' not found. 'create_addressGPT' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 347, in create_debtor
    return render(request, 'api/GPT/create_debtor.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_addressGPT' not found. 'create_addressGPT' is not a valid view function or pattern name.
ERROR 2025-04-20 04:11:58,180 log Internal Server Error: /app/gpt/create/debtor/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 347, in create_debtor
    return render(request, 'api/GPT/create_debtor.html', {'form': form})
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_addressGPT' not found. 'create_addressGPT' is not a valid view function or pattern name.
WARNING 2025-04-20 05:38:28,728 log Not Found: /favicon.ico
ERROR 2025-04-20 05:45:38,849 middleware Error en /app/sct/status/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/: cannot access local variable 'transfer' where it is not associated with a value
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.sct.models.SepaCreditTransfer.DoesNotExist: SepaCreditTransfer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 316, in check_transfer_status
    transfer = get_object_or_404(SepaCreditTransfer, payment_id=payment_id)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No SepaCreditTransfer matches the given query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 347, in check_transfer_status
    'transfer': transfer,
                ^^^^^^^^
UnboundLocalError: cannot access local variable 'transfer' where it is not associated with a value
ERROR 2025-04-20 05:45:38,854 log Internal Server Error: /app/sct/status/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.sct.models.SepaCreditTransfer.DoesNotExist: SepaCreditTransfer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 316, in check_transfer_status
    transfer = get_object_or_404(SepaCreditTransfer, payment_id=payment_id)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No SepaCreditTransfer matches the given query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 347, in check_transfer_status
    'transfer': transfer,
                ^^^^^^^^
UnboundLocalError: cannot access local variable 'transfer' where it is not associated with a value
WARNING 2025-04-20 05:48:29,329 log Bad Request: /app/gpt/transfer/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/cancel/
WARNING 2025-04-20 05:48:39,160 log Bad Request: /app/gpt/transfer/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/retry-auth/
WARNING 2025-04-20 05:48:49,400 log Method Not Allowed (POST): /app/gpt/transfer/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/delete/
ERROR 2025-04-20 05:49:05,693 middleware Error en /app/sct/status/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/: cannot access local variable 'transfer' where it is not associated with a value
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.sct.models.SepaCreditTransfer.DoesNotExist: SepaCreditTransfer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 316, in check_transfer_status
    transfer = get_object_or_404(SepaCreditTransfer, payment_id=payment_id)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No SepaCreditTransfer matches the given query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 347, in check_transfer_status
    'transfer': transfer,
                ^^^^^^^^
UnboundLocalError: cannot access local variable 'transfer' where it is not associated with a value
ERROR 2025-04-20 05:49:05,697 log Internal Server Error: /app/sct/status/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.sct.models.SepaCreditTransfer.DoesNotExist: SepaCreditTransfer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 316, in check_transfer_status
    transfer = get_object_or_404(SepaCreditTransfer, payment_id=payment_id)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No SepaCreditTransfer matches the given query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 347, in check_transfer_status
    'transfer': transfer,
                ^^^^^^^^
UnboundLocalError: cannot access local variable 'transfer' where it is not associated with a value
ERROR 2025-04-20 05:55:27,154 middleware Error en /app/sct/status/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/: cannot access local variable 'transfer' where it is not associated with a value
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.sct.models.SepaCreditTransfer.DoesNotExist: SepaCreditTransfer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 316, in check_transfer_status
    transfer = get_object_or_404(SepaCreditTransfer, payment_id=payment_id)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No SepaCreditTransfer matches the given query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 347, in check_transfer_status
    'transfer': transfer,
                ^^^^^^^^
UnboundLocalError: cannot access local variable 'transfer' where it is not associated with a value
ERROR 2025-04-20 05:55:27,159 log Internal Server Error: /app/sct/status/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.sct.models.SepaCreditTransfer.DoesNotExist: SepaCreditTransfer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 316, in check_transfer_status
    transfer = get_object_or_404(SepaCreditTransfer, payment_id=payment_id)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No SepaCreditTransfer matches the given query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/sct/process_xml_send2.py", line 347, in check_transfer_status
    'transfer': transfer,
                ^^^^^^^^
UnboundLocalError: cannot access local variable 'transfer' where it is not associated with a value
ERROR 2025-04-20 05:58:05,955 middleware Error en /app/gpt/transfer/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/pdf/: 'SepaCreditTransfer' object has no attribute 'creditor_name'
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 256, in generate_transfer_pdf
    pdf_path = generar_pdf_transferencia(transfer)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/generate_pdf.py", line 16, in generar_pdf_transferencia
    creditor_name = transfers.creditor_name.replace(" ", "_")
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SepaCreditTransfer' object has no attribute 'creditor_name'. Did you mean: 'creditor_agent'?
ERROR 2025-04-20 05:58:05,960 log Internal Server Error: /app/gpt/transfer/50d94e47-cfae-4cbc-a1af-06a67e3ea1d3/pdf/
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/views.py", line 256, in generate_transfer_pdf
    pdf_path = generar_pdf_transferencia(transfer)
  File "/home/kali/Documentos/Heroku/api_bank_heroku/api/gpt/generate_pdf.py", line 16, in generar_pdf_transferencia
    creditor_name = transfers.creditor_name.replace(" ", "_")
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SepaCreditTransfer' object has no attribute 'creditor_name'. Did you mean: 'creditor_agent'?
